### ISSUE TITLE
Hidapi

### ISSUE THREAD

**Issue by redDwarf03** [Sunbreak/logic_conf.dart#14]
Hello
I would like to send APDU commands to a device connected in USB
Using Hidapi seems a good way
I’ve found your lib for logic keyboard where you talk about the extraction of hidapi.dart

could you help me please to know how to use hidapi. 

Thank you 🙇🏻

**Comment by Sunbreak** [comment]
Any testable example or code?

**Comment by redDwarf03** [comment]
Which part do you want to test?
I could share the APDU part in this project : https://github.com/archethic-foundation/libdart/tree/master/lib/src/iso7816

**Comment by redDwarf03** [comment]
Nano S
VID : 0x2C97
PID : 0x0001

Nano X
VID : 0x2C97
PID : 0x0004

And the app in the ledger (work in progress): https://github.com/archethic-foundation/archethic-ledger

**Comment by Sunbreak** [comment]
I bought a Ledger Nano S just now. Hope it will arrive this week

https://github.com/LedgerHQ/ledgerjs for ReactNative maybe a better start point

**Comment by redDwarf03** [comment]
Oh great. I confess I’m not good with interoperability  between dart and another languages…
